Vagrant.configure("2") do |config|
  (1..2).each do |i|
      config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "node-#{i}.vagrant.io"
      node.vm.box = "centos/7"
      node.vm.network "private_network", ip: "192.168.50.1#{i}"
      node.ssh.username = "vagrant"
      node.ssh.insert_key = false
      node.vm.provision "shell" do |s|
      ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
      s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      SHELL
      end  
    end
  end



      config.vm.define "ansible" do |ansible|
      ansible.vm.hostname = "ansible.vagrant.io"
      ansible.vm.box = "centos/7"
      ansible.vm.network "private_network", ip: "192.168.50.8"
      ansible.ssh.username = "vagrant"
      ansible.ssh.insert_key = false

    ansible.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end  
end
end
